# Generated by Django 5.2.10 on 2026-01-31 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='bin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.bin'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.inventoryitem'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['bin', 'sku'], name='inventory_i_bin_id_213926_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['mode'], name='inventory_i_mode_4af791_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['updated_at'], name='inventory_i_updated_056069_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('bin', 'sku')},
        ),
    ]
