# Generated by Django 5.2.11 on 2026-02-28 08:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inventoryitem',
            name='inventory_i_mode_4af791_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventoryitem',
            name='inventory_i_updated_056069_idx',
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default='0.00', help_text='Vendor ko kitna paisa dena hai per unit', max_digits=10),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Agar Null hai, toh Company ka stock hai', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='mode',
            field=models.CharField(choices=[('owned', 'Owned Inventory (Company)'), ('consignment', 'Consignment (Vendor)'), ('virtual', 'Virtual Inventory (Drop-ship)')], default='owned', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['sku', 'created_at'], name='inventory_i_sku_942d12_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['owner'], name='inventory_i_owner_i_bf1a2e_idx'),
        ),
    ]
