# Generated by Django 5.2.11 on 2026-03-01 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_inventoryitem_inventory_i_mode_4af791_idx_and_more'),
        ('orders', '0006_remove_order_orders_orde_warehou_25bc40_idx_and_more'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='bin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='warehouse.bin'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.inventoryitem'),
        ),
    ]
