# Generated by Django 5.2.12 on 2026-03-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualPushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Example: 🏏 World Cup Mega Offer!', max_length=255)),
                ('message', models.TextField(help_text='Example: Order your snacks now and enjoy the match.')),
                ('topic', models.CharField(default='global', help_text="FCM Topic name. Default is 'global' (bhejne ke liye sabko). Aap 'promotions' bhi use kar sakte hain.", max_length=100)),
                ('extra_data', models.JSONField(blank=True, help_text='Optional JSON data for app routing. Example: {"target_url": "/offers"}', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False, help_text='Admin me save hote hi ye True ho jayega. (Read Only)')),
            ],
            options={
                'verbose_name': 'Manual Push Notification',
                'verbose_name_plural': 'Manual Push Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
