# Generated by Django 5.2.12 on 2026-03-11 19:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_manualpushnotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manualpushnotification',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='phoneotp',
            name='notificatio_phone_e61b0b_idx',
        ),
        migrations.RemoveField(
            model_name='manualpushnotification',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='manualpushnotification',
            name='is_sent',
        ),
        migrations.RemoveField(
            model_name='manualpushnotification',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='otpabuselog',
            name='last_attempt',
        ),
        migrations.AddField(
            model_name='manualpushnotification',
            name='selected_users',
            field=models.ManyToManyField(blank=True, help_text="Agar 'Selected Users' chuna hai, toh yahan se users select karein.", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manualpushnotification',
            name='sent',
            field=models.BooleanField(default=False, help_text='Status check ki push send ho chuka hai ya nahi.'),
        ),
        migrations.AddField(
            model_name='manualpushnotification',
            name='target_audience',
            field=models.CharField(choices=[('all', 'All Users (with App/Web)'), ('selected', 'Selected Users Only')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='manualpushnotification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='manualpushnotification',
            name='message',
            field=models.TextField(help_text='Notification ka main message'),
        ),
        migrations.AlterField(
            model_name='manualpushnotification',
            name='title',
            field=models.CharField(help_text='Notification ka title', max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='otpabuselog',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otpabuselog',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
