# Generated by Django 5.2.10 on 2026-01-31 18:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurgeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_multiplier', models.FloatField(default=2.0)),
                ('base_factor', models.FloatField(default=0.1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('warehouse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='surge_rule', to='warehouse.warehouse')),
            ],
        ),
    ]
