# Generated by Django 5.2.11 on 2026-03-01 19:18

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_cart_user_alter_cart_warehouse_and_more'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickingtask',
            old_name='target_bin',
            new_name='target_inventory_batch',
        ),
        migrations.AlterField(
            model_name='packingtask',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='pickingtask',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='picking_tasks', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='delivery_zone',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
