# Generated by Django 5.2.11 on 2026-02-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_store_open', models.BooleanField(default=True, help_text='Agar check mark hata denge toh store frontend par OFF ho jayega.')),
                ('store_closed_message', models.TextField(default='Sorry, we are currently closed. Please check back later.', help_text='Ye message users ko dikhega jab store OFF hoga.')),
            ],
            options={
                'verbose_name': 'Store Setting',
                'verbose_name_plural': 'Store Settings',
            },
        ),
    ]
