# Generated by Django 5.2.11 on 2026-03-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='is_store_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='store_closed_message',
            field=models.TextField(default='Sorry, we are currently closed. Please check back later.'),
        ),
    ]
