# Generated by Django 5.2.11 on 2026-02-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_fee_amount', models.DecimalField(decimal_places=2, default=15.0, help_text='Standard Delivery Charge (e.g. 15.00)', max_digits=10)),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=200.0, help_text='Kitne ki shopping par delivery free karni hai? (e.g. 200.00)', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order Configuration',
                'verbose_name_plural': 'Order Configurations',
            },
        ),
    ]
