# Generated by Django 5.2.11 on 2026-02-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=5.0, help_text='Standard delivery fee', max_digits=6)),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=100.0, help_text='Order amount above which delivery is free', max_digits=10)),
            ],
            options={
                'verbose_name': 'Order Configuration',
                'verbose_name_plural': 'Order Configurations',
            },
        ),
    ]
