# Generated by Django 5.2.11 on 2026-02-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderconfiguration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderconfiguration',
            name='delivery_fee_amount',
        ),
        migrations.RemoveField(
            model_name='orderconfiguration',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='orderconfiguration',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Standard delivery fee', max_digits=6),
        ),
        migrations.AlterField(
            model_name='orderconfiguration',
            name='free_delivery_threshold',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Order amount above which delivery is free', max_digits=10),
        ),
    ]
