# Generated by Django 5.2.11 on 2026-02-28 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_inventoryitem_inventory_i_mode_4af791_idx_and_more'),
        ('orders', '0003_orderconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemFulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_allocated', models.PositiveIntegerField()),
                ('vendor_payable_amount', models.DecimalField(decimal_places=2, default='0.00', help_text='Total amount to pay the vendor for this allocation', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_fulfillments', to='inventory.inventoryitem')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillments', to='orders.orderitem')),
            ],
        ),
    ]
