# Generated by Django 5.2.11 on 2026-02-28 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_cancel_reason_orderitem_status'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_warehou_25bc40_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='order',
            name='fulfillment_warehouse',
            field=models.ForeignKey(blank=True, help_text='Jahan inventory hai', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulfilled_orders', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_mile_warehouse',
            field=models.ForeignKey(blank=True, help_text='Rider pickup location', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='last_mile_orders', to='warehouse.warehouse'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('confirmed', 'Confirmed'), ('picking', 'Picking'), ('packed', 'Packed'), ('packed_at_hub', 'Packed at Mega Hub'), ('in_transit_to_local', 'In Transit to Dark Store'), ('received_at_local', 'Received at Dark Store'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='created', max_length=30),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['fulfillment_warehouse', 'status', 'created_at'], name='orders_orde_fulfill_ece9ca_idx'),
        ),
    ]
