# Generated by Django 5.2.11 on 2026-03-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_cart_user_alter_cart_warehouse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('express', 'Express Delivery'), ('standard', 'Standard Delivery')], max_length=20),
        ),
    ]
