# Generated by Django 5.2.10 on 2026-01-31 18:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('order_created', 'Order Created'), ('order_cancelled', 'Order Cancelled'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('refund_initiated', 'Refund Initiated'), ('refund_completed', 'Refund Completed'), ('delivery_completed', 'Delivery Completed'), ('delivery_failed', 'Delivery Failed'), ('manual_assignment', 'Manual Assignment'), ('admin_inventory_update', 'Admin Inventory Update'), ('gst_invoice_generated', 'GST Invoice Generated'), ('refund_failed', 'Refund Failed')], max_length=50)),
                ('reference_id', models.CharField(help_text='Order ID / Payment ID / Refund ID', max_length=100)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action'], name='audit_audit_action_86e815_idx'), models.Index(fields=['reference_id'], name='audit_audit_referen_856b09_idx')],
            },
        ),
    ]
