# Generated by Django 5.2.11 on 2026-03-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_banner_image_alter_brand_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Lower number comes first (e.g. 1 for Grocery, 2 for Electronics)'),
        ),
    ]
