# Generated by Django 5.2.11 on 2026-03-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_brand_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.CharField(blank=True, help_text="e.g., 'Contains Peanuts, Soy, Milk'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dietary_preference',
            field=models.CharField(choices=[('VEG', 'Vegetarian (Green Dot)'), ('NON_VEG', 'Non-Vegetarian (Red Dot)'), ('VEGAN', 'Vegan'), ('EGG', 'Contains Egg'), ('NONE', 'Not Applicable (e.g., Electronics/Cleaning)')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='eco_score',
            field=models.CharField(blank=True, help_text='Grade: A, B, C, D, E', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(blank=True, help_text='HSN / SAC Code for GST Billing', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_returnable',
            field=models.BooleanField(default=False, help_text='Can the customer return this item?'),
        ),
        migrations.AddField(
            model_name='product',
            name='max_order_quantity',
            field=models.PositiveIntegerField(default=10, help_text='Max items a customer can buy in one order'),
        ),
        migrations.AddField(
            model_name='product',
            name='nutri_score',
            field=models.CharField(blank=True, help_text='Grade: A, B, C, D, E', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging_type',
            field=models.CharField(blank=True, help_text='e.g., Plastic Packet, Glass Bottle, Cardboard', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='search_tags',
            field=models.TextField(blank=True, help_text='Comma separated keywords for better searching', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shelf_life',
            field=models.CharField(blank=True, help_text="e.g., 'Best before 6 months from manufacture'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(choices=[(0.0, '0% GST'), (5.0, '5% GST'), (12.0, '12% GST'), (18.0, '18% GST'), (28.0, '28% GST')], decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_in_grams',
            field=models.PositiveIntegerField(blank=True, help_text='Used to calculate rider bag capacity', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, help_text='Barcode / EAN / UPC', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default='1 Unit', help_text="Display text, e.g., '1 Kg', '500 g'", max_length=50),
        ),
    ]
