# Generated by Django 5.2.10 on 2026-01-31 18:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_status', models.CharField(choices=[('searching', 'Searching'), ('assigned', 'Assigned'), ('manual_intervention', 'Manual Intervention')], default='searching', max_length=20)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('picked_up', 'Picked Up'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='assigned', max_length=30)),
                ('otp', models.CharField(max_length=6)),
                ('proof_image', models.CharField(blank=True, max_length=255, null=True)),
                ('dispatch_location', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
