# Generated by Django 5.2.10 on 2026-01-31 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('orders', '0002_initial'),
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='riders.riderprofile'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(condition=models.Q(('status__in', ['assigned', 'picked_up', 'out_for_delivery'])), fields=['rider', 'status'], name='active_rider_delivery_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['rider', '-created_at'], name='delivery_de_rider_i_4d7627_idx'),
        ),
    ]
