# Generated by Django 5.2.11 on 2026-03-01 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_initial'),
        ('orders', '0006_remove_order_orders_orde_warehou_25bc40_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery', to='orders.order'),
        ),
    ]
