# Generated by Django 5.2.10 on 2026-01-31 18:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('missing_item', 'Missing Item'), ('damaged', 'Damaged Item'), ('late', 'Late Delivery'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='open', max_length=20)),
                ('admin_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=18)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=18)),
                ('house_no', models.CharField(help_text='Flat/House No', max_length=50)),
                ('floor_no', models.CharField(blank=True, help_text='Floor (Optional)', max_length=50)),
                ('apartment_name', models.CharField(blank=True, help_text='Building/Apartment Name', max_length=100)),
                ('landmark', models.CharField(blank=True, help_text='Nearby Landmark', max_length=100)),
                ('city', models.CharField(blank=True, help_text='City Name', max_length=100)),
                ('pincode', models.CharField(blank=True, help_text='Area Pincode', max_length=20)),
                ('google_address_text', models.TextField(help_text='Full address from Google Maps')),
                ('label', models.CharField(choices=[('HOME', 'Home'), ('WORK', 'Work'), ('OTHER', 'Other')], default='HOME', max_length=10)),
                ('receiver_name', models.CharField(blank=True, max_length=100)),
                ('receiver_phone', models.CharField(blank=True, max_length=15)),
                ('is_default', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.customerprofile')),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
