# Generated by Django 5.2.11 on 2026-03-01 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
        ('orders', '0006_remove_order_orders_orde_warehou_25bc40_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='apartment_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='floor_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='google_address_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='house_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='landmark',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='pincode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
