# Generated by Django 5.2.11 on 2026-03-01 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_cart_user_alter_cart_warehouse_and_more'),
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderearning',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='riderdocument',
            name='file_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='riderearning',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='riderearning',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earnings', to='riders.riderprofile'),
        ),
    ]
